spring.application.name=life tracker

server.port=6969

# DATABASE CONFIGURATIONS
spring.datasource.username=life_tracking_app
spring.datasource.password=life_tracker password
spring.datasource.url=jdbc:postgresql://localhost:5432/life_tracking_db
